layout: sidebar
style: dark
encoding: UTF-8
url: "https://mahis.life"

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

include: ['_pages', '/.well-known']

collections:
  - galleries

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 15
  exclude:
    archived: false
    forks: true
    projects:
    - Minify
    - marvin
    - Manga.py
    - learned-k-server
    - hierarchical-abm
    - covid19-r-simulations-lancet
    - puntender
    - uptime
    - Detic
    - LSeg
    - play-to-policy.github.io
    - bd-rt-dashboard
    - cv
    - google-scholar-scraper
    # - d3-books-timeline

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # youtube: your_username
  scholar: vAOw6aQAAAAJ
  linkedin: nshafiul
  twitter: notmahi
  keybase: mahi
  instagram: thesecondsonofman
  mastodon: "@notmahi"
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: https://mahis.life

topics:
  - name: Robotics
    web_url: https://dobb-e.com/
    image_url: /assets/images/icons/icons8-robot-120.png
    alt: "A small, happy robot"

  - name: Machine Learning
    web_url: https://mahis.life/bet/
    image_url: /assets/images/icons/icons8-deep-learning-64.png
    alt: "A neural network"

  - name: Philosophy
    web_url: https://mahis.life/2017/11/21/ministry-of-utmost-happiness-book-review/
    image_url: /assets/images/icons/icons8-philosophy-100.png
    alt: "The symbol Phi"

  - name: Writing and Photography
    web_url: https://thetech.com/photographers/mahi-shafiullah
    image_url: /assets/images/icons/icons8-photography-64.png
    alt: "A camera"

  - name: Literature
    web_url: https://www.goodreads.com/shafiullah
    image_url: /assets/images/icons/icons8-books-64.png
    alt: "A stack of books"

  - name: Dataviz
    web_url: https://mahis.life/d3-book-timeline/
    image_url: /assets/images/icons/icons8-data-visualization-64.png
    alt: "A bar chart"

quotes: true
